all:
	@dune exec ./test.exe
	@dune exec ./char_rnn.exe

square:
	@dune exec ./square.exe

shakespeare:
	wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt -O shakespeare.txt

miserables:
	wget https://www.gutenberg.org/cache/epub/17489/pg17489.txt -O miserables1.txt
	wget https://www.gutenberg.org/cache/epub/17489/pg17489.txt -O miserables2.txt
	wget https://www.gutenberg.org/cache/epub/17494/pg17494.txt -O miserables3.txt
	wget https://www.gutenberg.org/cache/epub/17494/pg17494.txt -O miserables4.txt
	wget https://www.gutenberg.org/cache/epub/17519/pg17519.txt -O miserables5.txt
